// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extern_map.proto

package com.google.javascript.gents.proto;

public final class ExternMap {
  private ExternMap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExternToTypingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gents.ExternToTyping)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; typings = 1;</code>
     */
    int getTypingsCount();
    /**
     * <code>map&lt;string, string&gt; typings = 1;</code>
     */
    boolean containsTypings(
        java.lang.String key);
    /**
     * Use {@link #getTypingsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getTypings();
    /**
     * <code>map&lt;string, string&gt; typings = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getTypingsMap();
    /**
     * <code>map&lt;string, string&gt; typings = 1;</code>
     */

    java.lang.String getTypingsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; typings = 1;</code>
     */

    java.lang.String getTypingsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code gents.ExternToTyping}
   */
  public  static final class ExternToTyping extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gents.ExternToTyping)
      ExternToTypingOrBuilder {
    // Use ExternToTyping.newBuilder() to construct.
    private ExternToTyping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExternToTyping() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExternToTyping(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                typings_ = com.google.protobuf.MapField.newMapField(
                    TypingsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              typings = input.readMessage(
                  TypingsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              typings_.getMutableMap().put(typings.getKey(), typings.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.javascript.gents.proto.ExternMap.internal_static_gents_ExternToTyping_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetTypings();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.javascript.gents.proto.ExternMap.internal_static_gents_ExternToTyping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.javascript.gents.proto.ExternMap.ExternToTyping.class, com.google.javascript.gents.proto.ExternMap.ExternToTyping.Builder.class);
    }

    public static final int TYPINGS_FIELD_NUMBER = 1;
    private static final class TypingsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.google.javascript.gents.proto.ExternMap.internal_static_gents_ExternToTyping_TypingsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> typings_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTypings() {
      if (typings_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TypingsDefaultEntryHolder.defaultEntry);
      }
      return typings_;
    }

    public int getTypingsCount() {
      return internalGetTypings().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; typings = 1;</code>
     */

    public boolean containsTypings(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTypings().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTypingsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTypings() {
      return getTypingsMap();
    }
    /**
     * <code>map&lt;string, string&gt; typings = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getTypingsMap() {
      return internalGetTypings().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; typings = 1;</code>
     */

    public java.lang.String getTypingsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTypings().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; typings = 1;</code>
     */

    public java.lang.String getTypingsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTypings().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetTypings().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        typings = TypingsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(1, typings);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetTypings().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        typings = TypingsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, typings);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.javascript.gents.proto.ExternMap.ExternToTyping)) {
        return super.equals(obj);
      }
      com.google.javascript.gents.proto.ExternMap.ExternToTyping other = (com.google.javascript.gents.proto.ExternMap.ExternToTyping) obj;

      boolean result = true;
      result = result && internalGetTypings().equals(
          other.internalGetTypings());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (!internalGetTypings().getMap().isEmpty()) {
        hash = (37 * hash) + TYPINGS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTypings().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.javascript.gents.proto.ExternMap.ExternToTyping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.javascript.gents.proto.ExternMap.ExternToTyping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.javascript.gents.proto.ExternMap.ExternToTyping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.javascript.gents.proto.ExternMap.ExternToTyping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.javascript.gents.proto.ExternMap.ExternToTyping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.javascript.gents.proto.ExternMap.ExternToTyping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.javascript.gents.proto.ExternMap.ExternToTyping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.javascript.gents.proto.ExternMap.ExternToTyping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.javascript.gents.proto.ExternMap.ExternToTyping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.javascript.gents.proto.ExternMap.ExternToTyping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.javascript.gents.proto.ExternMap.ExternToTyping prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gents.ExternToTyping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gents.ExternToTyping)
        com.google.javascript.gents.proto.ExternMap.ExternToTypingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.javascript.gents.proto.ExternMap.internal_static_gents_ExternToTyping_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetTypings();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableTypings();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.javascript.gents.proto.ExternMap.internal_static_gents_ExternToTyping_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.javascript.gents.proto.ExternMap.ExternToTyping.class, com.google.javascript.gents.proto.ExternMap.ExternToTyping.Builder.class);
      }

      // Construct using com.google.javascript.gents.proto.ExternMap.ExternToTyping.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableTypings().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.javascript.gents.proto.ExternMap.internal_static_gents_ExternToTyping_descriptor;
      }

      public com.google.javascript.gents.proto.ExternMap.ExternToTyping getDefaultInstanceForType() {
        return com.google.javascript.gents.proto.ExternMap.ExternToTyping.getDefaultInstance();
      }

      public com.google.javascript.gents.proto.ExternMap.ExternToTyping build() {
        com.google.javascript.gents.proto.ExternMap.ExternToTyping result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.javascript.gents.proto.ExternMap.ExternToTyping buildPartial() {
        com.google.javascript.gents.proto.ExternMap.ExternToTyping result = new com.google.javascript.gents.proto.ExternMap.ExternToTyping(this);
        int from_bitField0_ = bitField0_;
        result.typings_ = internalGetTypings();
        result.typings_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.javascript.gents.proto.ExternMap.ExternToTyping) {
          return mergeFrom((com.google.javascript.gents.proto.ExternMap.ExternToTyping)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.javascript.gents.proto.ExternMap.ExternToTyping other) {
        if (other == com.google.javascript.gents.proto.ExternMap.ExternToTyping.getDefaultInstance()) return this;
        internalGetMutableTypings().mergeFrom(
            other.internalGetTypings());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.javascript.gents.proto.ExternMap.ExternToTyping parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.javascript.gents.proto.ExternMap.ExternToTyping) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> typings_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetTypings() {
        if (typings_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TypingsDefaultEntryHolder.defaultEntry);
        }
        return typings_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableTypings() {
        onChanged();;
        if (typings_ == null) {
          typings_ = com.google.protobuf.MapField.newMapField(
              TypingsDefaultEntryHolder.defaultEntry);
        }
        if (!typings_.isMutable()) {
          typings_ = typings_.copy();
        }
        return typings_;
      }

      public int getTypingsCount() {
        return internalGetTypings().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; typings = 1;</code>
       */

      public boolean containsTypings(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTypings().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTypingsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getTypings() {
        return getTypingsMap();
      }
      /**
       * <code>map&lt;string, string&gt; typings = 1;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getTypingsMap() {
        return internalGetTypings().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; typings = 1;</code>
       */

      public java.lang.String getTypingsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTypings().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; typings = 1;</code>
       */

      public java.lang.String getTypingsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTypings().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTypings() {
        getMutableTypings().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; typings = 1;</code>
       */

      public Builder removeTypings(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableTypings().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableTypings() {
        return internalGetMutableTypings().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; typings = 1;</code>
       */
      public Builder putTypings(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableTypings().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; typings = 1;</code>
       */

      public Builder putAllTypings(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableTypings().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gents.ExternToTyping)
    }

    // @@protoc_insertion_point(class_scope:gents.ExternToTyping)
    private static final com.google.javascript.gents.proto.ExternMap.ExternToTyping DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.javascript.gents.proto.ExternMap.ExternToTyping();
    }

    public static com.google.javascript.gents.proto.ExternMap.ExternToTyping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ExternToTyping>
        PARSER = new com.google.protobuf.AbstractParser<ExternToTyping>() {
      public ExternToTyping parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ExternToTyping(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExternToTyping> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExternToTyping> getParserForType() {
      return PARSER;
    }

    public com.google.javascript.gents.proto.ExternMap.ExternToTyping getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gents_ExternToTyping_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gents_ExternToTyping_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gents_ExternToTyping_TypingsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gents_ExternToTyping_TypingsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020extern_map.proto\022\005gents\"u\n\016ExternToTyp" +
      "ing\0223\n\007typings\030\001 \003(\0132\".gents.ExternToTyp" +
      "ing.TypingsEntry\032.\n\014TypingsEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B#\n!com.google.j" +
      "avascript.gents.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gents_ExternToTyping_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gents_ExternToTyping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gents_ExternToTyping_descriptor,
        new java.lang.String[] { "Typings", });
    internal_static_gents_ExternToTyping_TypingsEntry_descriptor =
      internal_static_gents_ExternToTyping_descriptor.getNestedTypes().get(0);
    internal_static_gents_ExternToTyping_TypingsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gents_ExternToTyping_TypingsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
